package net.flamgop.gpu.state;

import static org.lwjgl.opengl.GL46.*;

public enum PixelStore {
    PACK_SWAP_BYTES(GL_PACK_SWAP_BYTES),
    PACK_LSB_FIRST(GL_PACK_LSB_FIRST),
    PACK_ROW_LENGTH(GL_PACK_ROW_LENGTH),
    PACK_IMAGE_HEIGHT(GL_PACK_IMAGE_HEIGHT),
    PACK_SKIP_PIXELS(GL_PACK_SKIP_PIXELS),
    PACK_SKIP_ROWS(GL_PACK_SKIP_ROWS),
    PACK_SKIP_IMAGES(GL_PACK_SKIP_IMAGES),
    PACK_ALIGNMENT(GL_PACK_ALIGNMENT),

    UNPACK_SWAP_BYTES(GL_UNPACK_SWAP_BYTES),
    UNPACK_LSB_FIRST(GL_UNPACK_LSB_FIRST),
    UNPACK_ROW_LENGTH(GL_UNPACK_ROW_LENGTH),
    UNPACK_IMAGE_HEIGHT(GL_UNPACK_IMAGE_HEIGHT),
    UNPACK_SKIP_PIXELS(GL_UNPACK_SKIP_PIXELS),
    UNPACK_SKIP_ROWS(GL_UNPACK_SKIP_ROWS),
    UNPACK_SKIP_IMAGES(GL_UNPACK_SKIP_IMAGES),
    UNPACK_ALIGNMENT(GL_UNPACK_ALIGNMENT),

    ;
    final int glQualifier;
    PixelStore(int glQualifier) {
        this.glQualifier = glQualifier;
    }
}
