package net.flamgop.gpu.state;

import static org.lwjgl.opengl.GL46.*;

public enum Capability {
    BLEND(GL_BLEND),
    CLIP_DISTANCE0(GL_CLIP_DISTANCE0),
    CLIP_DISTANCE1(GL_CLIP_DISTANCE1),
    CLIP_DISTANCE2(GL_CLIP_DISTANCE2),
    CLIP_DISTANCE3(GL_CLIP_DISTANCE3),
    CLIP_DISTANCE4(GL_CLIP_DISTANCE4),
    CLIP_DISTANCE5(GL_CLIP_DISTANCE5),
    CLIP_DISTANCE6(GL_CLIP_DISTANCE6),
    CLIP_DISTANCE7(GL_CLIP_DISTANCE7),
    COLOR_LOGIC_OP(GL_COLOR_LOGIC_OP),
    CULL_FACE(GL_CULL_FACE),
    DEBUG_OUTPUT(GL_DEBUG_OUTPUT),
    DEBUG_OUTPUT_SYNCHRONOUS(GL_DEBUG_OUTPUT_SYNCHRONOUS),
    DEPTH_CLAMP(GL_DEPTH_CLAMP),
    DEPTH_TEST(GL_DEPTH_TEST),
    DITHER(GL_DITHER),
    FRAMEBUFFER_SRGB(GL_FRAMEBUFFER_SRGB),
    LINE_SMOOTH(GL_LINE_SMOOTH),
    MULTISAMPLE(GL_MULTISAMPLE),
    POLYGON_OFFSET_FILL(GL_POLYGON_OFFSET_FILL),
    POLYGON_OFFSET_LINE(GL_POLYGON_OFFSET_LINE),
    POLYGON_OFFSET_POINT(GL_POLYGON_OFFSET_POINT),
    POLYGON_SMOOTH(GL_POLYGON_SMOOTH),
    PRIMITIVE_RESTART(GL_PRIMITIVE_RESTART),
    PRIMITIVE_RESTART_FIXED_INDEX(GL_PRIMITIVE_RESTART_FIXED_INDEX),
    PROGRAM_POINT_SIZE(GL_PROGRAM_POINT_SIZE),
    RASTERIZER_DISCARD(GL_RASTERIZER_DISCARD),
    SAMPLE_ALPHA_TO_COVERAGE(GL_SAMPLE_ALPHA_TO_COVERAGE),
    SAMPLE_ALPHA_TO_ONE(GL_SAMPLE_ALPHA_TO_ONE),
    SAMPLE_COVERAGE(GL_SAMPLE_COVERAGE),
    SAMPLE_MASK(GL_SAMPLE_MASK),
    SAMPLE_SHADING(GL_SAMPLE_SHADING),
    SCISSOR_TEST(GL_SCISSOR_TEST),
    STENCIL_TEST(GL_STENCIL_TEST),
    TEXTURE_CUBE_MAP_SEAMLESS(GL_TEXTURE_CUBE_MAP_SEAMLESS),

    ;
    final int glQualifier;

    Capability(int glQualifier) {
        this.glQualifier = glQualifier;
    }
}
